(in-package :cl-user)

(require :cocoa)

(defmacro progmain ((&rest bindings) &body b)
  (let* ((save (mapcar (lambda (v) (list (gensym) v)) bindings))
         (restore (mapcar 'reverse save)))
    `(let ,save (ccl::queue-for-event-process (lambda () (let ,restore ,@b ))))))

(ql:quickload :alexandria)
(ql:quickload :queues.simple-cqueue)
(ql:quickload :bordeaux-threads)
(ql:quickload :cl-json)
(ql:quickload :xmls)
(ql:quickload :chipz)
(ql:quickload :cl-base64)
(progmain ()
  (ql:quickload :cl-opengl)
  (ql:quickload :cl-glu)
  (ql:quickload :cl-glut) ;; am I even using this?
  (load "./runloop.lisp")
  (load "./render-buffer.lisp")
  (load "./render-buffer-instrs.lisp")
  (load "./matrix.lisp")
  (load "./display.lisp")
  (load "./texture.lisp")
  (load "./draw.lisp")
  (load "./node.lisp")
  (load "./action.lisp")
  (load "./action-manager.lisp")
  (load "./node-lifecycle.lisp")
  (load "./sprite.lisp")
  (load "./sprite-actions.lisp")
  (load "./animation-manager.lisp")
  (load "./sprite-animation.lisp")
  (load "./texture-packer.lisp")
  (load "./scratch-ccl.lisp") ;; really should be called "runtime-ccl"
  (load "./tmx-reader.lisp")
  (load "./tmx-renderer.lisp")
  )

